INFRA-2013 #comment adding docker-compose to the docker container.

diff --git a/alpine/Dockerfile b/alpine/Dockerfile
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -19,7 +19,6 @@
 #  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 #  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 #  THE SOFTWARE.
-
 FROM jenkinsci/jnlp-slave:alpine
 MAINTAINER Blaine Schanfeldt <git@blaines.me>
 # Root user is required to interact with Docker via docker.sock
@@ -27,13 +26,12 @@ USER root
 # BEGIN from Docker https://github.com/docker-library/docker/blob/master/17.06/Dockerfile
 RUN apk add --no-cache \
 		ca-certificates
-
 ENV DOCKER_CHANNEL stable
 ENV DOCKER_VERSION 17.06.0-ce
+ENV DOCKER_COMPOSE_VERSION 1.16.1
 # TODO ENV DOCKER_SHA256
 # https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
 # (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
-
 RUN set -ex; \
 # why we use "curl" instead of "wget":
 # + wget -O docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.03.1-ce.tgz
@@ -41,6 +39,7 @@ RUN set -ex; \
 # wget: error getting response: Connection reset by peer
 	apk add --no-cache --virtual .fetch-deps \
 		curl \
+		curl-dev \
 		tar \
 	; \
 	\
@@ -56,6 +55,10 @@ RUN set -ex; \
 		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
 		exit 1; \
 	fi; \
+	if ! curl -fL -o /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${dockerArch}"; then \
+		echo >&2 "error: failed to download 'docker-compose-${DOCKER_COMPOSE_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
 	\
 	tar --extract \
 		--file docker.tgz \
@@ -67,10 +70,9 @@ RUN set -ex; \
 	apk del .fetch-deps; \
 	\
 	dockerd -v; \
-	docker -v
-
+	docker -v; \
+    chmod +x /usr/local/bin/docker-compose;
 # END from Docker
-
 RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.4/community' >> /etc/apk/repositories \
   && apk --update add make \
   bash \
